image: gcc

build:
  stage: build

  script:
    - ./clean_cmake.sh
    - cd build
    - cmake ..
    - cd ..
    - make
  artifacts:
    paths:
      - mybinary


#test:
  #stage: test
  #script:
    #- 
