
image: gcc

build:
  stage: build

   before_script:
     - apt update && apt -y install make autoconf

  script:
    - g++ test.cpp -o mybinary
  artifacts:
    paths:
      - mybinary


test:
  stage: test
  script:
    - ./runmytests.sh
