macro(PrintIrrlichtFounded)
    if (IRRLICHT_FOUND)
        message("${Yellow}-- Found Irrlicht lib:")
        message("->  ${IRRLICHT_LIBRARIES}")
        message("${Yellow}-- Found Irrlicht include directory:")
        message("->  ${IRRLICHT_INCLUDE_DIRS}")
    endif(IRRLICHT_FOUND)
endmacro()

macro(GetIrrlichtPath)
    find_path(IRRLICHT_INCLUDE_DIR NAMES irrlicht.h PATHS /usr/include /usr/include/irrlicht /usr/local/include /usr/local/include/irrlicht /opt/local/include /sw/include /usr/lib64/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/local/lib/ /usr/local/lib64/ /usr/lib /usr/local/lib /opt/local/lib /sw/lib)
    if(IRRLICHT_INCLUDE_DIR STREQUAL "IRRLICHT_INCLUDE_DIR-NOTFOUND")
        unset(IRRLICHT_INCLUDE_DIR)
        find_path(IRRLICHT_INCLUDE_DIR NAMES irrlicht.h PATHS ${CMAKE_CURRENT_SOURCE_DIR}/libraries/irrlicht/includes)
    endif(IRRLICHT_INCLUDE_DIR STREQUAL "IRRLICHT_INCLUDE_DIR-NOTFOUND")
endmacro()

macro(CheckIfIrrlichtDll)
    find_path(IRRLICHT_DLL NAMES Irrlicht.dll PATHS ${CMAKE_CURRENT_SOURCE_DIR}/Release)
    find_path(IRRLICHT_DLL_DEBUG NAMES Irrlicht.dll PATHS ${CMAKE_CURRENT_SOURCE_DIR}/Debug)
    if (IRRLICHT_DLL_FOUND)
        message("${Yellow}-- Release: Irrlicht.dll found into:")
        message("->  ${IRRLICHT_DLL}")
    endif(IRRLICHT_DLL_FOUND)
    if (IRRLICHT_DLL_DEBUG_FOUND)
        message("${Yellow}-- Debug: Irrlicht.dll found into:")
        message("->  ${IRRLICHT_DLL}")
    endif(IRRLICHT_DLL_DEBUG_FOUND)
    if (IRRLICHT_DLL)
        set(IRRLICHT_DLL_FOUND TRUE)
    endif(IRRLICHT_DLL)
    if (IRRLICHT_DLL_DEBUG)
        set(IRRLICHT_DLL_DEBUG_FOUND TRUE)
    endif(IRRLICHT_DLL_DEBUG)
endmacro()

macro(GetIrrlichtLib)
    if (UNIX OR APPLE)
        find_library(IRRLICHT_LIBRARY NAMES Irrlicht PATHS /usr/include /usr/include/irrlicht /usr/local/include /usr/local/include/irrlicht /opt/local/include /sw/include /usr/lib64/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/local/lib/ /usr/local/lib64/ /usr/lib /usr/local/lib /opt/local/lib /sw/lib)
    endif (UNIX OR APPLE)
    if (NOT UNIX OR APPLE)
        file(GLOB_RECURSE IRRLICHT_LIBRARY PATHS ${CMAKE_CURRENT_SOURCE_DIR}/libraries/irrlicht Irrlicht.lib)
    endif(NOT UNIX OR APPLE)
endmacro()

macro(SetIrrlichtIncludeAndLib)
    set(IRRLICHT_INCLUDE_DIRS ${IRRLICHT_INCLUDE_DIR})
    set(IRRLICHT_LIBRARIES ${IRRLICHT_LIBRARIES} ${IRRLICHT_LIBRARY})
endmacro()

macro(PrintIrrlichtLoad)
    if (UNIX OR APPLE)
        if (IRRLICHT_INCLUDE_DIRS AND IRRLICHT_LIBRARIES)
            set(IRRLICHT_FOUND TRUE)
        endif (IRRLICHT_INCLUDE_DIRS AND IRRLICHT_LIBRARIES)
    endif (UNIX OR APPLE)
    if (NOT UNIX OR APPLE)
        if (IRRLICHT_INCLUDE_DIRS AND IRRLICHT_LIBRARIES AND IRRLICHT_DLL)
            set(IRRLICHT_FOUND TRUE)
        endif (IRRLICHT_INCLUDE_DIRS AND IRRLICHT_LIBRARIES AND IRRLICHT_DLL)
    endif (NOT UNIX OR APPLE)
endmacro()

PrintIrrlichtFounded()
GetIrrlichtPath()
GetIrrlichtLib()
if (NOT UNIX OR APPLE)
    CheckIfIrrlichtDll()
endif(NOT UNIX OR APPLE)
SetIrrlichtIncludeAndLib()
PrintIrrlichtLoad()